feat(react-query): next-app-router example with prefetch helpers (#5451)
* next-app-router example with prefetch helpers

* chore: apply lint and formatting fixes

* <Posts/>

* commity env

* readme

* why did autofixer do thsi?

* fix manypkg things...

* chore: apply lint and formatting fixes

* wtf linter???

* no infer

* skip this autolinter thing

* up

* wait query with nested suspense

* docs: update batching toggle docs (#5553)

* fix(server + client): skip referencing `NodeJS.*` (#5562)

* fix: Export required types for TypeScript workspaces (#5500)

* fix: Export required types for TypeScript workspaces

Exports additional types required to avoid Typescript compilation issues in TypeScript Workspace-based packages.

Fixes the following issue:
```
src/client/src/trpc.ts:8:14 - error TS2742: The inferred type of 'client' cannot be named without a reference to '../../../node_modules/@foobar/my-awesome-package/src/types'. This is likely not portable. A type annotation is necessary.

8 export const client = createTRPCClient<RootRouter>({
```

* fix(example): custom websocket server not upgrading due to next 13.4.3+ (#5563)

* chore: make dependabot understand bumps in `next`-tag (#5578)

* chore: bump pnpm (#5579)

* feat(server): add `experimental_caller()` (#5584)

* feat(server): add an `onError`-option to router caller (#5585)

* feat(next app dir): rethrow built-in Next errors (#5587)

* feat(server): add next.js `experimental_caller()`-adapter (#5589)

* return redirect (#5593)

* eh?

* this is technically more correct

* remark

* patch(server): bump `@fastify/websocket` to 10.0.1 (#5592)

* chore(docs): Update setup.mdx (#5594)

* feat: release v11 release candidate (#5601)

* patch(server): fix `dev --turbo` (#5604)

* fix(deps): update dependency eslint-plugin-unicorn to v52 (#5608)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* fix(react-query): use `optsRef` in `useSubscription` (#5610)

* fix(deps): update dependency @testing-library/dom to v10 (#5617)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* fix(server): remove extra export for router (#5621)

* docs: Add Ethereum DApp example (#5615)

* fix(deps): update dependency @testing-library/react to v15 (#5624)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* chore(deps): Remove unused dependency aws-lambda (#5628)

feat: Remove unused dependency aws-lambda

* chore: make sure test job runs on pushes (#5630)

* chore: fix codecov (#5631)

* patch(client): createInnerProxy exclude apply bind and call (#5629)


---------

Co-authored-by: bluecco <bluecco@gmail.com>

* chore: bump prisma (#5632)

* feat: export procedure types (#5640)

* chore: remove `name:` from jobs in ci (#5641)

* fix(deps): update dependency devalue to v5 (#5646)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* feat: Support Content Types other than JSON (FormData, File, Blob, Uint8Array)  (#5613)

* Add httpLink changes for various content-types

* Add content-handle and sync input reading

* set instead of append

* Successfully post data

* Support octet streams via Readable wrapper

* Add test case in demo app

* Add not implementeds to other adapters

* Switch getInputs->getInput with batch info passed through for efficient and lazy loading

* Add aws lambda json content handler

* Add json content handler to fetch adapter

* Add fastify json content type handler

* Remove body from HTTPRequest type

* Clean up restricted imports

* Tidy up content handlers

* Remove as any from http content handlers

* Fix in fetch and lambda adapters too

* whitespace

* Add names to content type handlers for debugging purposes

* Use 'void' trick with createContext to optionalise it without issues

* Add onError handler to server

* Fix fastify import

* Add minimal content types example to workspace

* Add TODO

* Structure universalRequesyter to reject requests of unsupported types

* Set body type properly on frontend

* PR cleanupg

* Remove exported experimental_ form data stuff

* Add support to httpBatchLink for non-json types

* Fix client types for File->Readable

* Apply changes from #5635

* Format

* Revert fetch utility type change since it breaks weirdly in that one place?

* Reintroduce userland splitLink for this

* Add contentTypeParsers with a Readable ZodEsque utility parser in

* Remove other type-casts and fix cirular import

* Make public and private API for handler options use a different createContext approach

* Fix: json content handlers should return undefined when rawInput is undefined

* Fix bug with query params being undefined in node http json handler

* Handle preprocessed inputs correctly

* Implement selectContentHandlerOrUnsupportedMediaType to ensure content-type is valid

* Fix formData tests

* Fix next.js payload too large test, 2 mistakes in the test itself

* Add content type to regression test

* Add content types to all fetch tests, fix awslambda content type case

* Formally remove input from TRPCRequestInfo

* Remove ReadableStream support as it doesn't work out the box and add tests for the Blob, File, Uint8Array

* Delete dead tests (for now)

* Fix Fetch Adapter's types around the createContext conditionality

* We don't use the King's English on the internet

* Document new APIs in use

* Remove node: imports

* Remove File check in favour of just Blob due to inheritance and nodejs support

* Remove redundant code

* Rephrase migration

* Rephrase error

* Support method override in universalRequester

* Add direction to new content type handling approach

* Remove File from parseOctetInput

* Add FileLike to support node 18

* Fix test

* Fix experiment next-formdata example

* fix: dump complex formdata stuff in favor of "using the platform" (#5652)

* chore: better error for mismatched content-type (#5654)

* better error for mismatched content-type

* update

* feat(react-query): expose `setQueriesData` in `useUtils` (#5605)


---------

Co-authored-by: Alex / KATT <alexander@n1s.se>

* Update migrate-from-v10-to-v11.mdx (#5655)

* Update migrate-from-v10-to-v11.mdx (#5656)

* fix: rollback formdata/octet type stream support (#5661)

* feat: add trpc-rabbitmq & trpc-mqtt to the awesome-trpc list (#5664)

* fix(deps): update dependency cssnano to v7 (#5669)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* feat(server): export `TRPCBuilder` class from `@trpc/server` package (#5670)

* chore: bump react version (#5680)

* chore: add secret to codecov (#5633)

* chore: fix codecov badge (#5689)

* chore: fix codecov for forks (#5688)

* feat(react-query): add support for global onSuccess for mutation (#5668)

* docs: fix link to the react query integration page  (#5693)

* feat: add formdata and octet stream support (#5665)

---------

Co-authored-by: KATT <alexander@n1s.se>

* chore(server): rewrite `resolveHTTPResponse` with Fetch (#5684)

---------

Co-authored-by: Nick Lucas <me@nicklucas.co.uk>
Co-authored-by: Sheraff <fpellet@ensc.fr>

* chore: tweak some comments (#5694)

* chore: trigger subtree after release (#5695)

* fix(deps): update dependency @headlessui/react to v2 (#5706)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* chore(server): use `Readable.fromWeb()` to pipe responses (#5701)

* fix(deps): update dependency eslint-plugin-unicorn to v53 (#5712)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* chore: bump react (#5720)

* feat(client): add `'none'` color option to default logger, add `withContext` option (#5714)

* feat(server): websocket keep alive (#5715)

* Fixes a single typo in docs (#5716)

* docs: add used by google (#5722)

* fix(server): handle large POST bodies in node-http (#5724)

* fix(server): handle large POST bodies in node-http

* Update packages/server/src/adapters/node-http/incomingMessageToRequest.ts

* feat(server + client): streaming mutations and queries over HTTP (#5700)

* Add trpc-cli to awesome-trpc (#5733)

* docs: update aws-lambda.md (#5740)

* rev

* updates

* rm dep

* try getting stream provider working

* chore: apply lint and formatting fixes

* this'd be neat

* okayyy

* nicee

* rm prefetchquery hoc

* rethrow

* reset lock

* revert autofixed stuff...

* chore: apply lint and formatting fixes

* disable autofixer

* release tmp

* clarify comments

* fix bad import paths

* hmm

* rm example in favor of current

* revert

* sync lock

* use shared getter

* dynammic

* fix build

* tsprune

* fix link

* update link in test

* test

* improve test accuracy

* rm

* data transforming

* niceee

* superjson

* bump tsq

* transformer.deserialize

* clarfiy

---------

Co-authored-by: autofix-ci[bot] <114827586+autofix-ci[bot]@users.noreply.github.com>
Co-authored-by: Alex / KATT <alexander@n1s.se>
Co-authored-by: Jeff Berry <jeff@catventuresllc.com>
Co-authored-by: Doug Kulak <dougkulak@gmail.com>
Co-authored-by: Victor Afanassieff <victor@afanassieff.com>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Akash <155352339+akashdevcc@users.noreply.github.com>
Co-authored-by: Mobin Mohanan <47410557+tr1sm0s1n@users.noreply.github.com>
Co-authored-by: AJ Stuyvenberg <astuyve@gmail.com>
Co-authored-by: bluecco <bluecco@gmail.com>
Co-authored-by: Andrei Karushev <infodusha@users.noreply.github.com>
Co-authored-by: Nick Lucas <Nick-Lucas@users.noreply.github.com>
Co-authored-by: Nabeel Valley <36758308+nabeelvalley@users.noreply.github.com>
Co-authored-by: Erwan d'Orgeville <info@erwandorgeville.com>
Co-authored-by: Nick <opiation@users.noreply.github.com>
Co-authored-by: Tomer Yechiel <32360493+tomer-yechiel@users.noreply.github.com>
Co-authored-by: Fedya Petrakov <jakephin2015@gmail.com>
Co-authored-by: Nick Lucas <me@nicklucas.co.uk>
Co-authored-by: Sheraff <fpellet@ensc.fr>
Co-authored-by: JonLuca De Caro <jonluca.decaro@gmail.com>
Co-authored-by: Burak Topbastekin <buraktt@users.noreply.github.com>
Co-authored-by: Babak Farkhoopak <44144724+babakfp@users.noreply.github.com>
Co-authored-by: Justin Carrus <carrus.justin@gmail.com>
Co-authored-by: Misha Kaletsky <15040698+mmkal@users.noreply.github.com>